### ISSUE TITLE
'Invalid cross-device link' on different mount points but the same device

### ISSUE THREAD

**Issue by YSunLIN** [arsenetar/send2trash#26]
On `Ubuntu 16.04`, you can reproduce it like this:
First, mount a directory to another directory on bash:
```shell
$ sudo mount --bind /vol/test /vol/test2
$ touch /vol/test2/rm.txt
```
Now, `/vol/test` and `/vol/test2` have the same device, but each of them mounts on different point.
```
$ mount
/dev/sdb1 on /vol type ext4 (rw,relatime,stripe=96,data=ordered)
/dev/sdb1 on /vol/test type ext4 (rw,relatime,stripe=96,data=ordered)
```

And then run the script below on python shell:
```python
from send2trash import send2trash
send2trash('/vol/test2/rm.txt')
```

Finally, you will get the error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/send2trash/plat_other.py", line 192, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/usr/local/lib/python2.7/dist-packages/send2trash/plat_other.py", line 103, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link
```

**Comment by vidartf** [comment]
[This SO answer](https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link) says that:

> os.rename only works if source and destination are on the same file system. You should use shutil.move instead.

But there are also comments saying that this does not work for their case. Maybe a `try`/`except` with fall back to copy + delete is best case?

**Comment by skupr-anaconda** [comment]
The same issue for `send2trash 1.7.1` on `ppc64le` with the `conda build` test environment:

```
TEST START: indexed-artifacts/noarch/send2trash-1.7.1-pyhd3eb1b0_1.tar.bz2
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /root/worker/containers/000014ksdia/tmp/build/a94a8fe5/send2trash_1624458701589/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla


The following NEW packages will be INSTALLED:

    _libgcc_mutex:         0.1-main                                                                                            
    ca-certificates:       2021.5.25-h6ffa863_1                                                                                
    ld_impl_linux-ppc64le: 2.33.1-h0f24833_7                                                                                   
    libffi:                3.3-he6710b0_2                                                                                      
    libgcc-ng:             8.2.0-h822a55f_1                                                                                    
    libstdcxx-ng:          8.2.0-h822a55f_1                                                                                    
    ncurses:               6.2-he6710b0_1                                                                                      
    openssl:               1.1.1k-h140841e_0                                                                                   
    python:                3.9.5-h836d2c2_3                                                                                    
    readline:              8.1-h140841e_0                                                                                      
    send2trash:            1.7.1-pyhd3eb1b0_1   file:///root/worker/containers/000014ksdia/tmp/build/a94a8fe5/indexed-artifacts
    sqlite:                3.35.4-hd7247d8_0                                                                                   
    tk:                    8.6.10-hbc83047_0                                                                                   
    tzdata:                2020f-h52ac0ba_0                                                                                    
    xz:                    5.2.5-h7b6447c_0                                                                                    
    zlib:                  1.2.11-h7b6447c_3                                                                                   

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/root/worker/containers/000014ksdia/tmp/build/a94a8fe5/send2trash_1624458701589/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
export SRC_DIR=/root/worker/containers/000014ksdia/tmp/build/a94a8fe5/send2trash_1624458701589/test_tmp
import: 'send2trash'
import: 'send2trash'
+ echo test
+ python -c 'from send2trash import *; send2trash('\''test.txt'\'')'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/worker/containers/000014ksdia/tmp/build/a94a8fe5/send2trash_1624458701589/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/root/worker/containers/000014ksdia/tmp/build/a94a8fe5/send2trash_1624458701589/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/send2trash/plat_other.py", line 116, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'test.txt' -> b'/root/worker/.Trash-0/files/test.txt'

Leaving build/test directories:
  Work:
 /root/worker/containers/000014ksdia/tmp/build/a94a8fe5/work 
  Test:
 /root/worker/containers/000014ksdia/tmp/build/a94a8fe5/test_tmp 
Leaving build/test environments:
  Test:
source activate  /root/worker/containers/000014ksdia/tmp/build/a94a8fe5/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol 
  Build:
source activate  /root/worker/containers/000014ksdia/tmp/build/a94a8fe5/_build_env 


TESTS FAILED: send2trash-1.7.1-pyhd3eb1b0_1.tar.bz2
```

**Comment by arsenetar** [comment]
Pre-release package at https://pypi.org/project/Send2Trash/1.8.1b0/ which fixed this problem for me in testing.
