### ISSUE TITLE
On windows, I cannot delete a file by absolute path

### ISSUE THREAD

**Issue by User670** [arsenetar/send2trash#86]
Python 3.10.0, Windows 10 x64 ("Microsoft Windows [version 10.0.19045.3448]").

I can delete files or folders by a relative path. For example, these all work:

```py
send2trash.send2trash("1.txt")
send2trash.send2trash("123/456")
send2trash.send2trash("../send2trash2/1.txt")
```

However I get errors when I try to delete by absolute path:

```
>>> send2trash.send2trash("D:/workspace/send2trash/123/456")
Traceback (most recent call last):
  File "C:\Users\User670\AppData\Local\Programs\Python\Python310\lib\site-packages\send2trash\plat_win_modern.py", line 59, in send2trash
    item = shell.SHCreateItemFromParsingName(path, None, shell.IID_IShellItem)
pywintypes.com_error: (-2147024809, '参数错误。', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User670\AppData\Local\Programs\Python\Python310\lib\site-packages\send2trash\plat_win_modern.py", line 69, in send2trash
    raise OSError(None, error.strerror, path, error.hresult)
OSError: [WinError -2147024809] 参数错误。: 'D:/workspace/send2trash/123/456'
```
where "参数错误" means "parameter error".

**Comment by wave-rider** [comment]
@User670 Hi
Can you try send2trash.send2trash(r"D:\workspace\send2trash\123\456") ?

**Comment by User670** [comment]
> @User670 Hi Can you try send2trash.send2trash(r"D:\workspace\send2trash\123\456") ?

Hmm this works. Thanks, I guess
